### ISSUE TITLE
[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument issue

### ISSUE THREAD

**Issue by pmor13** [kevinlawler/NSDate-TimeAgo#64]
Hi there!

I am trying to use NSDate-TimeAgo for the first time. I've reproduced all steps to set up it. But still have an exception

<code>[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument

Debuggingly I conclude that app crashes during execution of this line

<code>return [self stringFromFormat:@"%%d %@years ago" withValue:minutes];

How we can solve it?

**Comment by franklingu** [comment]
but for DateTools, I do think either clearly specify that even if cocoapods is used, we still need to drag the bundle over, or have this automatically solved...
