### ISSUE TITLE
I cannot import pod to Swift project

### ISSUE THREAD

**Issue by moyoteg** [kevinlawler/NSDate-TimeAgo#83]
I cannot import pod to Swift project for some reason, when trying to bridge it all I get is a "not found" error. What am I doing wrong? Thanks!!

**Comment by smasry** [comment]
Works fine for me.  
`#import "NSDate+TimeAgo.h"`

**Comment by davepatterson** [comment]
Simply adding `import NSDate_TimeAgo` to the .swift file you intend to use it in will work. There's no need to add `#import "NSDate+TimeAgo.h"` to your bridging header as `NSDate+TimeAgo` comes with an extension for swift.

**Comment by mohamede1945** [comment]
Actually, when you `import NSDate_TimeAgo` You will be using the Objective-c API not the swift API, see the [podspec here](https://github.com/kevinlawler/NSDate-TimeAgo/blob/master/NSDate%2BTimeAgo.podspec) only adds `'*.{h,m}'` objective-c files not swift files. So, to fix it we need to make it `'*.{h,m,swift}'`.

**Comment by mohamede1945** [comment]
Here is a screenshot of what has been added from the cocoapod.
<img width="413" alt="screen shot 2017-05-06 at 11 17 21 pm" src="https://cloud.githubusercontent.com/assets/5665498/25775984/43827f38-32b2-11e7-9fce-489535025154.png">
There is no swift files at all.

**Comment by dimohamdy** [comment]
@mohamede1945  podspec changed but there isn't any swift files  How you fix this?

**Comment by mohamede1945** [comment]
You can use objective-c classes just bridge your swift `Date` to `NSDate`.
Here is an example
```swift
import NSDate_TimeAgo

extension Date {
    func bookmarkTimeAgo() -> String? {
        return (self as NSDate).timeAgo(withLimit: 60 * 60 * 24 * 7, dateFormat: .full, andTimeFormat: .none)
    }
}
```

**Comment by mohamede1945** [comment]
Also, they updated the podspec, but they didn't release a new version on cocoapods.

**Comment by dimohamdy** [comment]
@mohamede1945  thanks
