### ISSUE TITLE
Push to Cocoapods Trunk

### ISSUE THREAD

**Issue by rad182** [kevinlawler/NSDate-TimeAgo#96]
hi @kevinlawler is there any reason why the latest version isn't pushed/published?
so we can stop doing to get the latest stable version :)
```ruby
 pod 'NSDate+TimeAgo', :git => 'https://github.com/kevinlawler/NSDate-TimeAgo'
```

**Comment by iblacksun** [comment]
+1

**Comment by kevinlawler** [comment]
If you open a pull request with what you need, I'll merge it. Otherwise this repo is only here for archival purposes.

**Comment by rad182** [comment]
@kevinlawler I don't think this can be done with pull request.
You just need to issue these commands

Set release tag
```
$ git tag '1.0.6'
$ git push --tags
```

Push to Cocoapods trunk
`pod trunk push NAME.podspec`

**Comment by kevinlawler** [comment]
Well, I set+pushed the release tag. I went through a couple steps in the CocoaPods process but timed out. I'll add rad182 as a contributor. Someone else has handled the CocoaPods stuff this far so I assume that can continue.

**Comment by rad182** [comment]
thanks @kevinlawler it seems this pod is still unclaimed. I will try to claim this repo as contributor so I can push changes or you might want to claim it yourself here https://trunk.cocoapods.org/claims/new ?

**Comment by kevinlawler** [comment]
you can claim

**Comment by rad182** [comment]
claimed and pushed the latest version `1.0.6` to Cocoapods Spec. thanks @kevinlawler for this awesome library!
